### ISSUE TITLE
Vortrag: Gliederung ausarbeiten

### ISSUE THREAD

**Issue by klemenstraeger** [htw-dresden-ps23/trommelhelden-web-frontend#39]

**Comment by qnicoq** [comment]
Erster grober Entwurf:
https://marshy-shadow-9ac.notion.site/Projektseminar-Vortrag-Gliederung-d2ee0b91ce75447a9788c359e859ccbc

**Comment by klemenstraeger** [comment]
Find ich gut. Bei Beispiel querys meinst du ja bestimmt den ablauf eines auftrages oder ? Also auftrag erstellen planen beenden
